language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install flake8
script:
  - flake8 bin/
  - shellcheck bin/generate_note bin/install_pkg bin/release bin/test
  - bin/test
